apiVersion: apps/v1
kind: Deployment
metadata:
  name: delayed-service-deployment
  labels:
    app: delayed-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delayed-service
  template:
    metadata:
      labels:
        app: delayed-service
    spec:
      containers:
        - name: delayed-service
          image: public.ecr.aws/r2n4f6g5/testproject:delayed-service-latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: delayed-service-service
spec:
  selector:
    app: delayed-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: public.ecr.aws/r2n4f6g5/testproject:gateway-latest
          ports:
            - containerPort: 8080
          env:
            - name: DELAYED_SERVICE_URL
              value: "http://delayed-service-service.default.svc.cluster.local:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
