services:
  gateway:
    build:
      context: ./apps/gateway
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      - DELAYED_SERVICE_URL=http://delayed_service:8080
    networks:
      - mocknet

  delayed_service:
    build:
      context: ./apps/delayed_service
    container_name: delayed_service
    networks:
      - mocknet

networks:
  mocknet: {}
